
import { Station, Sensor } from './types';

// --- Translations ---
export const DICTIONARY = {
  ar: {
    dashboard: 'لوحة التحكم',
    areas: 'رفع القراءات',
    stations: 'المحطات',
    sensors: 'الحساسات',
    reports: 'التقارير',
    'report-v1': 'تقرير الفاقد V1',
    readingReportTitle: 'تقرير القراءات للنقطة',
    readingReportSubtitle: 'اختر نقطة وحدد الفترة الزمنية لعرض التقرير التفصيلي',
    selectPointLabel: 'النقطة',
    dateFromLabel: 'من تاريخ',
    dateToLabel: 'إلى تاريخ',
    loadReport: 'عرض التقرير',
    totalReadings: 'إجمالي القراءات',
    avgFlowMetric: 'متوسط التدفق',
    totalizerDelta: 'فرق التوتلايزر',
    anomaliesTitle: 'الحالات الشاذة',
    highAnomalies: 'مرتفعة',
    lowAnomalies: 'منخفضة',
    normalAnomalies: 'طبيعي',
    chartFlowPressureTitle: 'منحنى التدفق والضغط',
    latestReadings: 'آخر القراءات',
    noReportData: 'لا توجد بيانات لهذا التقرير',
    selectPointPrompt: 'يرجى اختيار نقطة أولاً',
    addNewArea: 'إضافة منطقة جديدة',
    bulkImport: 'استيراد ملف إكسل',
    manualEntry: 'إدخال بيانات يدوي',
    dragDrop: 'اسحب وأفلت ملف الإكسل هنا',
    browseFiles: 'تصفح الملفات',
    mapHeaders: 'تعيين عناوين الأعمدة',
    column: 'عمود',
    headerName: 'اسم العنوان',
    previewData: 'معاينة البيانات',
    companyName: 'اسم الشركة',
    areaName: 'اسم المنطقة (DMZ)',
    areaCode: 'كود المنطقة (DMZ)',
    time: 'الوقت',
    lineCount: 'عدد الخطوط',
    valveCount: 'عدد الفتحات',
    meterCount: 'عدد العدادات',
    areaSize: 'المساحة (m2)',
    managerName: 'اسم المشغل / المسؤول',
    readingsStartMonth: 'عدد قراءات أول الشهر',
    readingsStartYear: 'عدد قراءات أول السنة',
    latitude: 'خط العرض',
    longitude: 'خط الطول',
    uploadImage: 'رفع صورة المنطقة',
    selectLocation: 'تحديد الموقع على الخريطة',
    save: 'حفظ البيانات',
    cancel: 'إلغاء',
    pressure: 'الضغط',
    bar: 'بار',
    status: 'الحالة',
    lastReading: 'آخر قراءة',
    consumption24h: 'استهلاك 24 ساعة',
    pipe: 'خط',
    stationDetails: 'تفاصيل المحطة',
    liveMonitoring: 'مراقبة حية',
    viewDetails: 'عرض التفاصيل',
    alertHigh: 'ضغط مرتفع',
    alertLow: 'ضغط منخفض',
    normal: 'طبيعي',
    sensorDetails: 'تفاصيل الحساس',
    historyGraph: 'سجل الضغوط (آخر 24 ساعة)',
    flowRate: 'التدفق',
    search: 'بحث...',
    name: 'الاسم',
    total3M: 'إجمالي 3 شهور',
    date: 'التاريخ',
    themeDark: 'الوضع الليلي',
    themeLight: 'الوضع النهاري',
    logout: 'تسجيل خروج',
    profile: 'الملف الشخصي',
    monthlyConsumption: 'الاستهلاك الشهري',
    pressureAnomalies: 'شذوذ الضغط',
    averagePressure: 'متوسط الضغط',
    activeSensors: 'الحساسات النشطة',
    totalAlerts: 'إجمالي التنبيهات',
    exportPDF: 'تصدير PDF',
    exportCSV: 'تصدير CSV',
    detectedPressureSpikes: 'تم اكتشاف ارتفاع مفاجئ في الضغط يتجاوز (7.5 بار). يرجى فحص الصمامات.',
    checkValveIntegrity: 'تحقق من سلامة الصمام.',
    systemOverview: 'نظرة عامة على النظام',
    criticalAlerts: 'تنبيهات حرجة',
    step1Upload: '1. رفع الملف',
    step2Map: '2. تعيين الأعمدة',
    selectField: 'اختر الحقل...',
    ignoreColumn: 'تجاهل العمود',
    importSuccess: 'تم استيراد البيانات بنجاح',
    processing: 'جارِ المعالجة...',
    fileName: 'اسم الملف',
    fileSize: 'الحجم',
    rowCount: 'عدد الصفوف',
    continueToMap: 'متابعة لتعيين الأعمدة',
    removeFile: 'حذف الملف',
    downloadTemplate: 'تحميل نموذج فارغ',
    noHeaderMode: 'وضع ملف بدون عناوين (الصف الأول يحتوي على بيانات)',
    notifications: 'الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات جديدة',
    editProfile: 'تعديل الملف الشخصي',
    personalInfo: 'المعلومات الشخصية',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    role: 'الوظيفة',
    saveChanges: 'حفظ التغييرات',
    modeExcel: 'استيراد Excel',
    modeManual: 'إدخال يدوي',
    locationOnMap: 'الموقع على الخريطة',
    clickToSelect: 'انقر لتحديد الموقع',
    appearance: 'المظهر',
    colorTheme: 'لون النظام',
    cursorStyle: 'شكل المؤشر',
    loginTitle: 'مرحباً بعودتك',
    loginSubtitle: 'قم بتسجيل الدخول للوصول إلى لوحة التحكم',
    loginButton: 'تسجيل الدخول',
    password: 'كلمة المرور',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    loginServerError: 'حدث خطأ أثناء تسجيل الدخول. حاول مرة أخرى.',
    forgotPassword: 'نسيت كلمة المرور؟',
    newPage: 'صفحة جديدة',
    permissions: 'الصلاحيات',
    permissionsPageTitle: 'إدارة الصلاحيات والمجموعات',
    permissionsPageSubtitle: 'تعيين صلاحيات Django لكل مجموعة مستخدم',
    fieldPermissions: 'صلاحيات الحقول',
    fieldPermissionsLoadFailed: 'تعذر تحميل صلاحيات الحقول',
    fieldPermissionsUpdateSuccess: 'تم حفظ صلاحية الحقل بنجاح',
    fieldPermissionsUpdateError: 'تعذر حفظ صلاحية الحقل',
    viewPermission: 'عرض',
    editPermission: 'تحرير',
    hidePermission: 'إخفاء',
    sessionSummary: 'بيانات الجلسة',
    sessionPermissions: 'الصلاحيات المرتبطة بالمستخدم',
    noSessionPermissions: 'لم يتم إرجاع صلاحيات في استجابة تسجيل الدخول.',
    userIdLabel: 'معرف المستخدم',
    tokenLabel: 'رمز الدخول',
    availablePermissions: 'كافة الصلاحيات',
    searchPermissions: 'بحث في الصلاحيات...',
    groupSelectorLabel: 'المجموعات',
    groupSelectorPlaceholder: 'اختر مجموعة',
    groupAutoSelectHint: 'اختيار مجموعة سيعرض صلاحياتها تلقائياً',
    groupsLoadFailed: 'تعذر تحميل المجموعات',
    groupLoadFailed: 'تعذر تحميل صلاحيات المجموعة',
    groupSelectionRequired: 'اختر مجموعة للتحديث أولاً',
    refreshGroups: 'تحديث المجموعات',
    selectAll: 'تحديد الكل',
    clearSelection: 'مسح التحديد',
    groupNameLabel: 'اسم المجموعة',
    operationLabel: 'نوع العملية',
    createNew: 'إنشاء (POST)',
    updateExisting: 'تحديث (PUT)',
    saveGroup: 'حفظ صلاحيات المجموعة',
    selectedCount: 'عدد المحدد',
    permissionsLoadFailed: 'تعذر تحميل الصلاحيات. تأكد من تسجيل الدخول كموظف.',
    permissionsSaveSuccess: 'تم حفظ صلاحيات المجموعة بنجاح',
    permissionsSaveError: 'تعذر حفظ صلاحيات المجموعة',
    noPermissionsFound: 'لا توجد صلاحيات مطابقة للبحث',
    staffOnly: 'هذه الصفحة تتطلب صلاحيات مدير النظام (Superadmin).',
    users: 'المستخدمون',
    usersPageTitle: 'إدارة المستخدمين',
    usersPageSubtitle: 'هذه الصفحة مخصصة للمشرف العام فقط (Superadmin)',
    usersLoadFailed: 'تعذر تحميل المستخدمين',
    pointsLoadFailed: 'تعذر تحميل النقاط',
    assignGroup: 'إسناد إلى مجموعة',
    selectGroup: 'اختر المجموعة',
    currentGroup: 'المجموعة الحالية',
    assignSuccess: 'تم إسناد المستخدم إلى المجموعة بنجاح',
    assignError: 'تعذر إسناد المستخدم إلى المجموعة',
    assignGroupSelectionRequired: 'اختر مجموعة أولاً',
    companies: 'الشركات',
    dm: 'المناطق DM',
    provinces: 'المحافظات',
    centers: 'المراكز',
    villages: 'القرى',
    deviceTypes: 'أنواع الأجهزة',
    measureTypes: 'أنواع القياس',
    measureDevices: 'أجهزة القياس',
    points: 'النقاط',
    readings: 'القراءات',
    setPoints: 'نقاط الضبط',
    dmaFieldSurveys: 'مسوحات DMA',
    dmzNetworkData: 'بيانات شبكة DM',
    units: 'الوحدات',
    connectionTypes: 'أنواع الاتصال',
    'damietta-map': 'خريطة دمياط',
    'water-valves': 'محابس المياه',
    filters: 'الفلاتر',
    selectFilter: 'اختر فلتر',
    companyDetails: 'تفاصيل الشركة',
    editCompany: 'تعديل الشركة',
    refresh: 'تحديث',
    tableFullName: 'الاسم الكامل',
    tableRole: 'الوظيفة',
    tableDepartment: 'القسم',
    tableJoiningDate: 'تاريخ الانضمام',
    tableStatus: 'الحالة',
    tableSalary: 'الراتب',
    tableActive: 'نشط',
    tableActions: 'الإجراءات',
    addNew: 'إضافة جديد',
    searchPlaceholder: 'ابحث بالاسم أو الوظيفة أو القسم...',
    rowsLabel: 'صف',
    noRows: 'لا توجد بيانات',
    edit: 'تعديل',
    delete: 'حذف',
    addRowTitle: 'إضافة صف جديد',
    editRowTitle: 'تعديل الصف',
    confirmDelete: 'هل تأكد من حذف هذا الصف؟',
    pleaseProvideNameRole: 'يرجى إدخال الاسم والوظيفة',
    prev: 'السابق',
    next: 'التالي',
    showing: 'عرض',
    of: 'من',
    tableInactive: 'غير نشط',
    page: 'صفحة',
    validation_id_required: 'المعرف مطلوب',
    validation_must_be_number: 'يجب أن يكون رقمًا',
    validation_invalid_email: 'بريد إلكتروني غير صالح',
    validation_invalid_phone: 'رقم هاتف غير صالح',
    validation_invalid_url: 'رابط غير صالح (ابدأ بـ http:// أو https://)',
    validation_fix_errors: 'يرجى تصحيح الأخطاء قبل الحفظ',
    validation_required: 'هذا الحقل مطلوب',
  },
  en: {
    dashboard: 'Dashboard',
    areas: 'Areas Management',
    stations: 'Stations',
    sensors: 'Sensors',
    reports: 'Reports',
    'report-v1': 'Loss report V1',
    readingReportTitle: 'Point Reading Report',
    readingReportSubtitle: 'Pick a point and optional date range to fetch readings',
    selectPointLabel: 'Point',
    dateFromLabel: 'Date from',
    dateToLabel: 'Date to',
    loadReport: 'Load report',
    totalReadings: 'Total readings',
    avgFlowMetric: 'Avg flow',
    totalizerDelta: 'Totalizer delta',
    anomaliesTitle: 'Anomalies',
    highAnomalies: 'High',
    lowAnomalies: 'Low',
    normalAnomalies: 'Normal',
    chartFlowPressureTitle: 'Flow & Pressure trend',
    latestReadings: 'Latest readings',
    noReportData: 'No data for this report',
    selectPointPrompt: 'Select a point to view a report',
    addNewArea: 'Add New Area',
    bulkImport: 'Import Excel File',
    manualEntry: 'Manual Data Entry',
    dragDrop: 'Drag & Drop Excel file here',
    browseFiles: 'Browse Files',
    mapHeaders: 'Map Column Headers',
    column: 'Column',
    headerName: 'Header Name',
    previewData: 'Data Preview',
    companyName: 'Company Name',
    areaName: 'Area Name (DMZ)',
    areaCode: 'Area Code (DMZ)',
    time: 'Time',
    lineCount: 'Number of Lines',
    valveCount: 'Number of Valves',
    meterCount: 'Number of Meters',
    areaSize: 'Area Size (m²)',
    managerName: 'Manager Name',
    readingsStartMonth: 'Readings Start of Month',
    readingsStartYear: 'Readings Start of Year',
    latitude: 'Latitude',
    longitude: 'Longitude',
    uploadImage: 'Upload Area Image',
    selectLocation: 'Select on Map',
    save: 'Save Data',
    cancel: 'Cancel',
    pressure: 'Pressure',
    bar: 'Bar',
    status: 'Status',
    lastReading: 'Last Reading',
    consumption24h: '24h Consumption',
    pipe: 'Pipe',
    stationDetails: 'Station Details',
    liveMonitoring: 'Live Monitoring',
    viewDetails: 'View Details',
    alertHigh: 'High Pressure',
    alertLow: 'Low Pressure',
    normal: 'Normal',
    sensorDetails: 'Sensor Details',
    historyGraph: 'Pressure History (Last 24h)',
    flowRate: 'Flow',
    search: 'Search...',
    name: 'Name',
    total3M: 'Total 3M',
    date: 'Date',
    themeDark: 'Dark Mode',
    themeLight: 'Light Mode',
    logout: 'Logout',
    profile: 'Profile',
    monthlyConsumption: 'Monthly Consumption',
    pressureAnomalies: 'Pressure Anomalies',
    averagePressure: 'Avg Pressure',
    activeSensors: 'Active Sensors',
    totalAlerts: 'Total Alerts',
    exportPDF: 'Export PDF',
    exportCSV: 'Export CSV',
    detectedPressureSpikes: 'Detected pressure spikes above normal threshold (7.5 Bar).',
    checkValveIntegrity: 'Check valve integrity.',
    systemOverview: 'System Overview',
    criticalAlerts: 'Critical Alerts',
    step1Upload: '1. Upload File',
    step2Map: '2. Map Columns',
    selectField: 'Select Field...',
    ignoreColumn: 'Ignore Column',
    importSuccess: 'Data Imported Successfully',
    processing: 'Processing...',
    fileName: 'File Name',
    fileSize: 'Size',
    rowCount: 'Row Count',
    continueToMap: 'Continue to Mapping',
    removeFile: 'Remove File',
    downloadTemplate: 'Download Template',
    noHeaderMode: 'No-Header Mode (First row contains data)',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No new notifications',
    editProfile: 'Edit Profile',
    personalInfo: 'Personal Information',
    email: 'Email Address',
    phone: 'Phone Number',
    role: 'Role',
    saveChanges: 'Save Changes',
    modeExcel: 'Excel Import',
    modeManual: 'Manual Entry',
    locationOnMap: 'Location on Map',
    clickToSelect: 'Click to select location',
    appearance: 'Appearance',
    colorTheme: 'System Color',
    cursorStyle: 'Cursor Style',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to access the dashboard',
    loginButton: 'Sign In',
    password: 'Password',
    invalidCredentials: 'Invalid email or password',
    loginServerError: 'Unable to sign in right now. Please try again.',
    forgotPassword: 'Forgot Password?',
    newPage: 'New Page',
    permissions: 'Permissions',
    permissionsPageTitle: 'Permissions & Groups',
    permissionsPageSubtitle: 'Assign Django permissions to groups',
    fieldPermissions: 'Field permissions',
    fieldPermissionsLoadFailed: 'Failed to load field permissions',
    fieldPermissionsUpdateSuccess: 'Field permission saved',
    fieldPermissionsUpdateError: 'Failed to save field permission',
    viewPermission: 'View',
    editPermission: 'Edit',
    hidePermission: 'Hide',
    sessionSummary: 'Session summary',
    sessionPermissions: 'Permissions from login response',
    noSessionPermissions: 'No permission summary was returned on login.',
    userIdLabel: 'User ID',
    tokenLabel: 'Token',
    availablePermissions: 'All permissions',
    searchPermissions: 'Search permissions...',
    groupSelectorLabel: 'Groups',
    groupSelectorPlaceholder: 'Select a group',
    groupAutoSelectHint: 'Choose a group to auto-load its permissions.',
    groupsLoadFailed: 'Could not load groups list',
    groupLoadFailed: 'Could not load group permissions',
    groupSelectionRequired: 'Select a group before updating',
    refreshGroups: 'Refresh groups',
    selectAll: 'Select all',
    clearSelection: 'Clear selection',
    groupNameLabel: 'Group name',
    operationLabel: 'Operation',
    createNew: 'Create (POST)',
    updateExisting: 'Update (PUT)',
    saveGroup: 'Save group permissions',
    selectedCount: 'Selected',
    permissionsLoadFailed: 'Could not load permissions. Make sure you are staff.',
    permissionsSaveSuccess: 'Group permissions saved successfully',
    permissionsSaveError: 'Unable to save group permissions',
    noPermissionsFound: 'No permissions match this search',
    staffOnly: 'Superadmin permissions are required for this page.',
    users: 'Users',
    usersPageTitle: 'Users',
    usersPageSubtitle: 'Visible to superadmin only',
    usersLoadFailed: 'Could not load users',
    pointsLoadFailed: 'Could not load points',
    assignGroup: 'Assign to group',
    selectGroup: 'Select group',
    currentGroup: 'Current group',
    assignSuccess: 'User assigned to group successfully',
    assignError: 'Could not assign user to group',
    assignGroupSelectionRequired: 'Select a group first',
    companies: 'Companies',
    dm: 'DM',
    provinces: 'Provinces',
    centers: 'Centers',
    villages: 'Villages',
    deviceTypes: 'Device Types',
    measureTypes: 'Measure Types',
    measureDevices: 'Measure Devices',
    points: 'Points',
    readings: 'Readings',
    setPoints: 'Set Points',
    dmaFieldSurveys: 'DMA Field Surveys',
    dmzNetworkData: 'DM Network Data',
    units: 'Units',
    connectionTypes: 'Connection Types',
    'damietta-map': 'Damietta map',
    'water-valves': 'Water valves',
    filters: 'Filters',
    selectFilter: 'Select filter',
    companyDetails: 'Company Details',
    editCompany: 'Edit Company',
    refresh: 'Refresh',
    tableFullName: 'Full Name',
    tableRole: 'Role',
    tableDepartment: 'Department',
    tableJoiningDate: 'Joining Date',
    tableStatus: 'Status',
    tableSalary: 'Salary',
    tableActive: 'Active',
    tableActions: 'Actions',
    addNew: 'Add New',
    searchPlaceholder: 'Search by name, role, department...',
    rowsLabel: 'rows',
    noRows: 'No rows',
    edit: 'Edit',
    delete: 'Delete',
    addRowTitle: 'Add New Row',
    editRowTitle: 'Edit Row',
    confirmDelete: 'Are you sure you want to delete this row?',
    pleaseProvideNameRole: 'Please provide name and role',
    prev: 'Prev',
    next: 'Next',
    showing: 'Showing',
    of: 'of',
    tableInactive: 'Inactive',
    page: 'Page',
    validation_id_required: 'ID is required',
    validation_must_be_number: 'Must be a number',
    validation_invalid_email: 'Invalid email',
    validation_invalid_phone: 'Invalid phone',
    validation_invalid_url: 'Invalid URL (must start with http:// or https://)',
    validation_fix_errors: 'Please fix validation errors before saving',
    validation_required: 'This field is required',
  }
};

// --- Mock Data Generators ---
const generateHistory = () => {
  const data = [];
  for (let i = 0; i < 24; i++) {
    data.push({
      time: `${i}:00`,
      value: Math.max(2, Math.min(8, 5 + (Math.random() * 2 - 1)))
    });
  }
  return data;
};

const createSensor = (id: string, name: string, lineName: string): Sensor => ({
  id,
  name,
  lineName,
  pressure: parseFloat((4 + Math.random() * 3).toFixed(2)),
  status: Math.random() > 0.8 ? 'warning' : 'normal',
  lastReadingCurrent: new Date().toLocaleString(),
  lastReadingPrevious: new Date(Date.now() - 86400000).toLocaleString(),
  total3MCurrent: Math.floor(Math.random() * 10000),
  total3MPrevious: Math.floor(Math.random() * 9000),
  dailyConsumption: Math.floor(Math.random() * 500),
  history: generateHistory(),
});

export const MOCK_STATIONS: Station[] = [
  {
    id: 'st-1',
    name: 'Main Pump Station - North',
    areaId: 'area-1',
    status: 'active',
    pipes: [
      {
        id: 'p-1',
        name: 'Main Line A',
        sensors: [
          createSensor('s-1', 'Inlet Valve', 'Main Line A'),
          createSensor('s-2', 'Midpoint 1', 'Main Line A'),
          createSensor('s-3', 'Outlet Valve', 'Main Line A'),
        ]
      },
      {
        id: 'p-2',
        name: 'Distribution B',
        sensors: [
          createSensor('s-4', 'Pressure Sensor 1', 'Distribution B'),
          createSensor('s-5', 'Flow Sensor', 'Distribution B'),
        ]
      }
    ]
  },
  {
    id: 'st-2',
    name: 'Desalination Sub-station',
    areaId: 'area-1',
    status: 'maintenance',
    pipes: [
      {
        id: 'p-3',
        name: 'Treatment Pipe',
        sensors: [
          createSensor('s-6', 'Treatment Inlet', 'Treatment Pipe'),
          createSensor('s-7', 'Filter 1', 'Treatment Pipe'),
          createSensor('s-8', 'Treatment Outlet', 'Treatment Pipe'),
        ]
      }
    ]
  }
];

export const MOCK_DYNAMIC_SCHEMA = {
  entityName: 'Employee',
  fields: [
    { name: 'id', label: 'ID', type: 'text', required: true, hidden: true },
    { name: 'fullName', label: 'Full Name', type: 'text', required: true },
    { name: 'role', label: 'Role', type: 'select', required: true, options: ['Admin', 'Manager', 'User'] },
    { name: 'department', label: 'Department', type: 'text', required: false },
    { name: 'joiningDate', label: 'Joining Date', type: 'date', required: true },
    { name: 'isActive', label: 'Active', type: 'boolean', required: true },
    { name: 'salary', label: 'Salary', type: 'number', required: false },
  ]
};

export const MOCK_DYNAMIC_DATA = [
  { id: 'EMP001', fullName: 'Ahmed Ali', role: 'Manager', department: 'HR', joiningDate: '2023-01-15', isActive: true, salary: 5000 },
  { id: 'EMP002', fullName: 'Sara Smith', role: 'Admin', department: 'IT', joiningDate: '2022-11-01', isActive: true, salary: 8000 },
  { id: 'EMP003', fullName: 'John Doe', role: 'User', department: 'Sales', joiningDate: '2023-03-10', isActive: false, salary: 4000 },
  { id: 'EMP004', fullName: 'Fatima Noor', role: 'User', department: 'Marketing', joiningDate: '2023-06-20', isActive: true, salary: 4500 },
  { id: 'EMP005', fullName: 'Khaled Omar', role: 'Manager', department: 'Operations', joiningDate: '2021-05-05', isActive: true, salary: 6000 },
];
