

import { Station, Sensor, Notification } from './types';

// --- Translations ---
export const DICTIONARY = {
  ar: {
    dashboard: 'لوحة التحكم',
    areas: 'إدارة المناطق',
    stations: 'المحطات',
    sensors: 'الحساسات',
    reports: 'التقارير',
    addNewArea: 'إضافة منطقة جديدة',
    bulkImport: 'استيراد ملف إكسل',
    manualEntry: 'إدخال بيانات يدوي',
    dragDrop: 'اسحب وأفلت ملف الإكسل هنا',
    browseFiles: 'تصفح الملفات',
    mapHeaders: 'تعيين عناوين الأعمدة',
    column: 'عمود',
    headerName: 'اسم العنوان',
    previewData: 'معاينة البيانات',
    companyName: 'اسم الشركة',
    areaName: 'اسم المنطقة (DMZ)',
    areaCode: 'كود المنطقة (DMZ)',
    lineCount: 'عدد الخطوط',
    valveCount: 'عدد الفتحات',
    meterCount: 'عدد العدادات',
    areaSize: 'المساحة (m2)',
    managerName: 'اسم المشغل / المسؤول',
    readingsStartMonth: 'عدد قراءات أول الشهر',
    readingsStartYear: 'عدد قراءات أول السنة',
    latitude: 'خط العرض',
    longitude: 'خط الطول',
    uploadImage: 'رفع صورة المنطقة',
    selectLocation: 'تحديد الموقع على الخريطة',
    save: 'حفظ البيانات',
    cancel: 'إلغاء',
    pressure: 'الضغط',
    bar: 'بار',
    status: 'الحالة',
    lastReading: 'آخر قراءة',
    consumption24h: 'استهلاك 24 ساعة',
    pipe: 'خط',
    stationDetails: 'تفاصيل المحطة',
    liveMonitoring: 'مراقبة حية',
    viewDetails: 'عرض التفاصيل',
    alertHigh: 'ضغط مرتفع',
    alertLow: 'ضغط منخفض',
    normal: 'طبيعي',
    sensorDetails: 'تفاصيل الحساس',
    historyGraph: 'سجل الضغوط (آخر 24 ساعة)',
    search: 'بحث...',
    name: 'الاسم',
    total3M: 'إجمالي 3 شهور',
    date: 'التاريخ',
    themeDark: 'الوضع الليلي',
    themeLight: 'الوضع النهاري',
    logout: 'تسجيل خروج',
    profile: 'الملف الشخصي',
    monthlyConsumption: 'الاستهلاك الشهري',
    pressureAnomalies: 'شذوذ الضغط',
    averagePressure: 'متوسط الضغط',
    activeSensors: 'الحساسات النشطة',
    totalAlerts: 'إجمالي التنبيهات',
    exportPDF: 'تصدير PDF',
    exportCSV: 'تصدير CSV',
    detectedPressureSpikes: 'تم اكتشاف ارتفاع مفاجئ في الضغط يتجاوز (7.5 بار). يرجى فحص الصمامات.',
    checkValveIntegrity: 'تحقق من سلامة الصمام.',
    systemOverview: 'نظرة عامة على النظام',
    criticalAlerts: 'تنبيهات حرجة',
    step1Upload: '1. رفع الملف',
    step2Map: '2. تعيين الأعمدة',
    selectField: 'اختر الحقل...',
    ignoreColumn: 'تجاهل العمود',
    importSuccess: 'تم استيراد البيانات بنجاح',
    processing: 'جارِ المعالجة...',
    fileName: 'اسم الملف',
    fileSize: 'الحجم',
    rowCount: 'عدد الصفوف',
    continueToMap: 'متابعة لتعيين الأعمدة',
    removeFile: 'حذف الملف',
    downloadTemplate: 'تحميل نموذج فارغ',
    noHeaderMode: 'وضع ملف بدون عناوين (الصف الأول يحتوي على بيانات)',
    notifications: 'الإشعارات',
    markAllRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات جديدة',
    editProfile: 'تعديل الملف الشخصي',
    personalInfo: 'المعلومات الشخصية',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    role: 'الوظيفة',
    saveChanges: 'حفظ التغييرات',
    modeExcel: 'استيراد Excel',
    modeManual: 'إدخال يدوي',
    locationOnMap: 'الموقع على الخريطة',
    clickToSelect: 'انقر لتحديد الموقع',
    appearance: 'المظهر',
    colorTheme: 'لون النظام',
    cursorStyle: 'شكل المؤشر',
    loginTitle: 'مرحباً بعودتك',
    loginSubtitle: 'قم بتسجيل الدخول للوصول إلى لوحة التحكم',
    loginButton: 'تسجيل الدخول',
    password: 'كلمة المرور',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    forgotPassword: 'نسيت كلمة المرور؟',
  },
  en: {
    dashboard: 'Dashboard',
    areas: 'Areas Management',
    stations: 'Stations',
    sensors: 'Sensors',
    reports: 'Reports',
    addNewArea: 'Add New Area',
    bulkImport: 'Import Excel File',
    manualEntry: 'Manual Data Entry',
    dragDrop: 'Drag & Drop Excel file here',
    browseFiles: 'Browse Files',
    mapHeaders: 'Map Column Headers',
    column: 'Column',
    headerName: 'Header Name',
    previewData: 'Data Preview',
    companyName: 'Company Name',
    areaName: 'Area Name (DMZ)',
    areaCode: 'Area Code (DMZ)',
    lineCount: 'Number of Lines',
    valveCount: 'Number of Valves',
    meterCount: 'Number of Meters',
    areaSize: 'Area Size (m²)',
    managerName: 'Manager Name',
    readingsStartMonth: 'Readings Start of Month',
    readingsStartYear: 'Readings Start of Year',
    latitude: 'Latitude',
    longitude: 'Longitude',
    uploadImage: 'Upload Area Image',
    selectLocation: 'Select on Map',
    save: 'Save Data',
    cancel: 'Cancel',
    pressure: 'Pressure',
    bar: 'Bar',
    status: 'Status',
    lastReading: 'Last Reading',
    consumption24h: '24h Consumption',
    pipe: 'Pipe',
    stationDetails: 'Station Details',
    liveMonitoring: 'Live Monitoring',
    viewDetails: 'View Details',
    alertHigh: 'High Pressure',
    alertLow: 'Low Pressure',
    normal: 'Normal',
    sensorDetails: 'Sensor Details',
    historyGraph: 'Pressure History (Last 24h)',
    search: 'Search...',
    name: 'Name',
    total3M: 'Total 3M',
    date: 'Date',
    themeDark: 'Dark Mode',
    themeLight: 'Light Mode',
    logout: 'Logout',
    profile: 'Profile',
    monthlyConsumption: 'Monthly Consumption',
    pressureAnomalies: 'Pressure Anomalies',
    averagePressure: 'Avg Pressure',
    activeSensors: 'Active Sensors',
    totalAlerts: 'Total Alerts',
    exportPDF: 'Export PDF',
    exportCSV: 'Export CSV',
    detectedPressureSpikes: 'Detected pressure spikes above normal threshold (7.5 Bar).',
    checkValveIntegrity: 'Check valve integrity.',
    systemOverview: 'System Overview',
    criticalAlerts: 'Critical Alerts',
    step1Upload: '1. Upload File',
    step2Map: '2. Map Columns',
    selectField: 'Select Field...',
    ignoreColumn: 'Ignore Column',
    importSuccess: 'Data Imported Successfully',
    processing: 'Processing...',
    fileName: 'File Name',
    fileSize: 'Size',
    rowCount: 'Row Count',
    continueToMap: 'Continue to Mapping',
    removeFile: 'Remove File',
    downloadTemplate: 'Download Template',
    noHeaderMode: 'No-Header Mode (First row contains data)',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No new notifications',
    editProfile: 'Edit Profile',
    personalInfo: 'Personal Information',
    email: 'Email Address',
    phone: 'Phone Number',
    role: 'Role',
    saveChanges: 'Save Changes',
    modeExcel: 'Excel Import',
    modeManual: 'Manual Entry',
    locationOnMap: 'Location on Map',
    clickToSelect: 'Click to select location',
    appearance: 'Appearance',
    colorTheme: 'System Color',
    cursorStyle: 'Cursor Style',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to access the dashboard',
    loginButton: 'Sign In',
    password: 'Password',
    invalidCredentials: 'Invalid email or password',
    forgotPassword: 'Forgot Password?',
  }
};

// --- Mock Data Generators ---

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: '1', title: 'High Pressure Alert', message: 'Pressure exceeded 8.5 bar in Main Line A.', time: '10 min ago', type: 'alert', read: false },
  { id: '2', title: 'Maintenance Required', message: 'Desalination Sub-station scheduled for service.', time: '2 hours ago', type: 'info', read: false },
  { id: '3', title: 'Report Generated', message: 'Monthly consumption report is ready for download.', time: '1 day ago', type: 'success', read: true },
];

const generateHistory = () => {
  const data = [];
  for (let i = 0; i < 24; i++) {
    data.push({
      time: `${i}:00`,
      value: Math.max(2, Math.min(8, 5 + (Math.random() * 2 - 1)))
    });
  }
  return data;
};

const createSensor = (id: string, name: string, lineName: string): Sensor => ({
  id,
  name,
  lineName,
  pressure: parseFloat((4 + Math.random() * 3).toFixed(2)),
  status: Math.random() > 0.8 ? 'warning' : 'normal',
  lastReadingCurrent: new Date().toLocaleString(),
  lastReadingPrevious: new Date(Date.now() - 86400000).toLocaleString(),
  total3MCurrent: Math.floor(Math.random() * 10000),
  total3MPrevious: Math.floor(Math.random() * 9000),
  dailyConsumption: Math.floor(Math.random() * 500),
  history: generateHistory(),
});

export const MOCK_STATIONS: Station[] = [
  {
    id: 'st-1',
    name: 'Main Pump Station - North',
    areaId: 'area-1',
    status: 'active',
    pipes: [
      {
        id: 'p-1',
        name: 'Main Line A',
        sensors: [
          createSensor('s-1', 'Inlet Valve', 'Main Line A'),
          createSensor('s-2', 'Midpoint 1', 'Main Line A'),
          createSensor('s-3', 'Outlet Valve', 'Main Line A'),
        ]
      },
      {
        id: 'p-2',
        name: 'Distribution B',
        sensors: [
          createSensor('s-4', 'Pressure Sensor 1', 'Distribution B'),
          createSensor('s-5', 'Flow Sensor', 'Distribution B'),
        ]
      }
    ]
  },
  {
    id: 'st-2',
    name: 'Desalination Sub-station',
    areaId: 'area-1',
    status: 'maintenance',
    pipes: [
      {
        id: 'p-3',
        name: 'Treatment Pipe',
        sensors: [
          createSensor('s-6', 'Treatment Inlet', 'Treatment Pipe'),
          createSensor('s-7', 'Filter 1', 'Treatment Pipe'),
          createSensor('s-8', 'Treatment Outlet', 'Treatment Pipe'),
        ]
      }
    ]
  }
];

export const MOCK_DYNAMIC_SCHEMA = {
  entityName: 'Employee',
  fields: [
    { name: 'id', label: 'ID', type: 'text', required: true, hidden: true },
    { name: 'fullName', label: 'Full Name', type: 'text', required: true },
    { name: 'role', label: 'Role', type: 'select', required: true, options: ['Admin', 'Manager', 'User'] },
    { name: 'department', label: 'Department', type: 'text', required: false },
    { name: 'joiningDate', label: 'Joining Date', type: 'date', required: true },
    { name: 'isActive', label: 'Active', type: 'boolean', required: true },
    { name: 'salary', label: 'Salary', type: 'number', required: false },
  ]
};

export const MOCK_DYNAMIC_DATA = [
  { id: 'EMP001', fullName: 'Ahmed Ali', role: 'Manager', department: 'HR', joiningDate: '2023-01-15', isActive: true, salary: 5000 },
  { id: 'EMP002', fullName: 'Sara Smith', role: 'Admin', department: 'IT', joiningDate: '2022-11-01', isActive: true, salary: 8000 },
  { id: 'EMP003', fullName: 'John Doe', role: 'User', department: 'Sales', joiningDate: '2023-03-10', isActive: false, salary: 4000 },
  { id: 'EMP004', fullName: 'Fatima Noor', role: 'User', department: 'Marketing', joiningDate: '2023-06-20', isActive: true, salary: 4500 },
  { id: 'EMP005', fullName: 'Khaled Omar', role: 'Manager', department: 'Operations', joiningDate: '2021-05-05', isActive: true, salary: 6000 },
];
